services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: shiz-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: shiz-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"